config/routes.rb
SmartPatient::Application.routes.draw do

  get "search/doctors"
  get "ajax/fetch_location"
  get "ajax/set_current_position"
  get "ajax/update_doctors_data"
  devise_for :users
  resources :doctors
  resources :invitations

  get "doctor_sessions/new_session", as: :new_doctors_session
  get "doctor_sessions/create"
  get "doctor_sessions/live", as: :live_session
  get "welcome/index"

  # You can have the root of your site routed with "root"
  root 'welcome#index'

  controller :modals do
       get '/suggestions' => :suggestions
  end


end

app/models/invitation.rb
# == Schema Information
#
# Table name: invitations
#
#  id         :integer          not null, primary key
#  doctor_id  :string(255)
#  user_id    :string(255)
#  status     :string(255)
#  created_at :datetime
#  updated_at :datetime
#

class Invitation < ActiveRecord::Base
  has_one :doctor_session
  belongs_to :doctor
  belongs_to :user

  def create_doctor_session
      DoctorSession.create!({
          doctor_id: doctor_id,
          patient_id: user_id,
          status: 'ACCEPTED',
          invitation_id: self.id

                             })
  end

  after_create :create_doctor_session

end

app/controllers/invitations_controller.rb
class InvitationsController < ApplicationController
  before_action :set_invitation, only: [:show, :edit, :update, :destroy]

  # GET /invitations
  # GET /invitations.json
  def index
    @invitations = Invitation.all
  end

  # GET /invitations/1
  # GET /invitations/1.json
  def show
  end

  # GET /invitations/new
  def new
    @invitation = Invitation.new
  end

  # GET /invitations/1/edit
  def edit
  end

  # POST /invitations
  # POST /invitations.json
  def create
    @invitation = Invitation.new(invitation_params)

    respond_to do |format|
      if @invitation.save
        format.html { redirect_to @invitation, notice: 'Invitation was successfully created.' }
        format.json { render action: 'show', status: :created, location: @invitation }
      else
        format.html { render action: 'new' }
        format.json { render json: @invitation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /invitations/1
  # PATCH/PUT /invitations/1.json
  def update
    respond_to do |format|
      if @invitation.update(invitation_params)
        format.html { redirect_to @invitation, notice: 'Invitation was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @invitation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /invitations/1
  # DELETE /invitations/1.json
  def destroy
    @invitation.destroy
    respond_to do |format|
      format.html { redirect_to invitations_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_invitation
      @invitation = Invitation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def invitation_params
      params[:invitation]
    end
end

app/helpers/invitations_helper.rb
module InvitationsHelper
end

app/views/invitations/_form.html.erb
<%= form_for(@invitation) do |f| %>
  <% if @invitation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@invitation.errors.count, "error") %> prohibited this invitation from being saved:</h2>

      <ul>
      <% @invitation.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/invitations/edit.html.erb
<h1>Editing invitation</h1>

<%= render 'form' %>

<%= link_to 'Show', @invitation %> |
<%= link_to 'Back', invitations_path %>

app/views/invitations/index.html.erb
<div class="clear1"></div>
<div class="clear1"></div>
<div class="clear1"></div>
<div class="clear1"></div>
<table class="table table-bordered">
  <thead>
    <tr>
      <th>Doctor</th>
      <th>Time</th>
      <th>URL</th>
    </tr>
  </thead>

  <tbody>
    <% @invitations.each do |invitation| %>
      <tr>
       <td><%= invitation.doctor.professional_name %></td>
       <td class="label label-warning">Today</td>
       <td><%= link_to 'Counseling URL', live_session_path(i_id: invitation.id) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Invitation', new_invitation_path %>

app/views/invitations/new.html.erb
<h1>New invitation</h1>

<%= render 'form' %>

<%= link_to 'Back', invitations_path %>

app/views/invitations/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_invitation_path(@invitation) %> |
<%= link_to 'Back', invitations_path %>