config/routes.rb
SmartPatient::Application.routes.draw do

  get "search/doctors"
  get "ajax/fetch_location"
  get "ajax/set_current_position"
  get "ajax/update_doctors_data"
  devise_for :users
  resources :doctors
  resources :invitations

  get "doctor_sessions/new_session", as: :new_doctors_session
  get "doctor_sessions/create"
  get "doctor_sessions/live", as: :live_session
  get "welcome/index"

  # You can have the root of your site routed with "root"
  root 'welcome#index'

  controller :modals do
       get '/suggestions' => :suggestions
  end


end

app/models/doctor.rb
# == Schema Information
#
# Table name: doctors
#
#  id                    :integer          not null, primary key
#  name                  :string(255)
#  title                 :string(255)
#  experience            :string(255)
#  active                :boolean          default(TRUE)
#  doc_code              :string(255)
#  password_digest       :string(255)
#  age                   :string(255)
#  tag_line              :string(255)
#  created_at            :datetime
#  updated_at            :datetime
#  online                :boolean
#  latitude              :decimal(10, 6)
#  longitude             :decimal(10, 6)
#  street_address        :string(255)
#  city                  :string(255)
#  state                 :string(255)
#  country               :string(255)
#  counseling_hour_start :time
#  counseling_hour_end   :time
#

class Doctor < ActiveRecord::Base

  include Constants

  has_secure_password

  validates_presence_of :password, :on => :create
  validates :doc_code, :uniqueness => true
  validates :tag_line, :title, :experience, :age, presence: true

  geocoded_by :street_address   # can also be an IP address
  after_validation :geocode

  #reverse_geocoded_by :latitude, :longitude
  #after_validation :reverse_geocode

  def professional_name
    "#{title.humanize} #{name}"
  end

  def available_now?
    online || false
  end


end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController
  before_action :set_doctor, only: [:show, :edit, :update, :destroy]

  # GET /doctors
  # GET /doctors.json
  def index
    @doctors = Doctor.all
  end

  # GET /doctors/1
  # GET /doctors/1.json
  def show
  end

  # GET /doctors/new
  def new
    @doctor = Doctor.new
  end

  # GET /doctors/1/edit
  def edit
  end

  # POST /doctors
  # POST /doctors.json
  def create
    @doctor = Doctor.new(doctor_params)

    respond_to do |format|
      if @doctor.save
        format.html { redirect_to @doctor, notice: 'Doctor was successfully created.' }
        format.json { render action: 'show', status: :created, location: @doctor }
      else
        format.html { render action: 'new' }
        format.json { render json: @doctor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /doctors/1
  # PATCH/PUT /doctors/1.json
  def update
    respond_to do |format|
      if @doctor.update(doctor_params)
        format.html { redirect_to @doctor, notice: 'Doctor was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @doctor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /doctors/1
  # DELETE /doctors/1.json
  def destroy
    @doctor.destroy
    respond_to do |format|
      format.html { redirect_to doctors_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_doctor
      @doctor = Doctor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def doctor_params
      params.require(:doctor).permit(:name, :title, :experience, :active, :doc_code, :password_digest, :age)
    end
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/views/doctors/_form.html.erb
<%= form_for(@doctor) do |f| %>
  <% if @doctor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@doctor.errors.count, "error") %> prohibited this doctor from being saved:</h2>

      <ul>
      <% @doctor.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :experience %><br>
    <%= f.text_field :experience %>
  </div>
  <div class="field">
    <%= f.label :active %><br>
    <%= f.check_box :active %>
  </div>
  <div class="field">
    <%= f.label :doc_code %><br>
    <%= f.text_field :doc_code %>
  </div>
  <div class="field">
    <%= f.label :password_digest %><br>
    <%= f.text_field :password_digest %>
  </div>
  <div class="field">
    <%= f.label :age %><br>
    <%= f.text_field :age %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/doctors/edit.html.erb
<h1>Editing doctor</h1>

<%= render 'form' %>

<%= link_to 'Show', @doctor %> |
<%= link_to 'Back', doctors_path %>

app/views/doctors/index.html.erb
<h1>Listing doctors</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Title</th>
      <th>Experience</th>
      <th>Active</th>
      <th>Doc code</th>
      <th>Password digest</th>
      <th>Age</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @doctors.each do |doctor| %>
      <tr>
        <td><%= doctor.name %></td>
        <td><%= doctor.title %></td>
        <td><%= doctor.experience %></td>
        <td><%= doctor.active %></td>
        <td><%= doctor.doc_code %></td>
        <td><%= doctor.password_digest %></td>
        <td><%= doctor.age %></td>
        <td><%= link_to 'Show', doctor %></td>
        <td><%= link_to 'Edit', edit_doctor_path(doctor) %></td>
        <td><%= link_to 'Destroy', doctor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Doctor', new_doctor_path %>

app/views/doctors/new.html.erb
<h1>New doctor</h1>

<%= render 'form' %>

<%= link_to 'Back', doctors_path %>

app/views/doctors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @doctor.name %>
</p>

<p>
  <strong>Title:</strong>
  <%= @doctor.title %>
</p>

<p>
  <strong>Experience:</strong>
  <%= @doctor.experience %>
</p>

<p>
  <strong>Active:</strong>
  <%= @doctor.active %>
</p>

<p>
  <strong>Doc code:</strong>
  <%= @doctor.doc_code %>
</p>

<p>
  <strong>Password digest:</strong>
  <%= @doctor.password_digest %>
</p>

<p>
  <strong>Age:</strong>
  <%= @doctor.age %>
</p>

<%= link_to 'Edit', edit_doctor_path(@doctor) %> |
<%= link_to 'Back', doctors_path %>